import SettingsController from '@/wayfinder/actions/App/Http/Controllers/Client/Servers/SettingsController'
import { queryOptions, useQuery } from '@tanstack/react-query'
import byteSize from 'byte-size'

import { type DataResponse, apiFetch } from '@/lib/api'

// Live filesystem usage comes from the shared `useServerResources` hook (detail/api.ts) — no
// duplicate reader here.

export type StorageDevice = App.Data.Server.StorageDeviceData

export interface ServerStorage {
    /** Every device attached to the server, in the order PVE reports them. */
    devices: StorageDevice[]
    /** Interfaces, in the order they are tried at boot. A subset of `devices`. */
    bootOrder: string[]
}

export const getStorage = async (uuid: string): Promise<ServerStorage> => {
    const { data } = await apiFetch<
        DataResponse<App.Data.Server.ServerStorageData>
    >(SettingsController.getStorage(uuid))

    return { devices: data.devices, bootOrder: data.bootOrder }
}

export const updateBootOrder = async (
    uuid: string,
    order: string[]
): Promise<void> => {
    await apiFetch(SettingsController.updateBootOrder(uuid), {
        body: { order },
    })
}

export const storageQueries = {
    all: (uuid: string) => ['servers', uuid, 'storage'] as const,
    detail: (uuid: string) =>
        queryOptions({
            queryKey: storageQueries.all(uuid),
            queryFn: () => getStorage(uuid),
        }),
}

export const useStorage = (uuid: string) =>
    useQuery(storageQueries.detail(uuid))

/**
 * What a device *is*, in the terms a user would use for it.
 *
 * PVE only distinguishes disk from cdrom, which leaves the cloud-init drive —
 * a 4 MiB cdrom every server has and nobody put there — indistinguishable from
 * installation media the user mounted on purpose.
 */
export type DeviceKind = 'disk' | 'cdrom' | 'cloudinit'

export const deviceKind = (device: StorageDevice): DeviceKind => {
    if (device.isCloudinitDrive) return 'cloudinit'

    return device.media === 'cdrom' ? 'cdrom' : 'disk'
}

export const deviceKindLabels: Record<DeviceKind, string> = {
    disk: 'Disk',
    cdrom: 'CD-ROM',
    cloudinit: 'Cloud-init',
}

export const formatBytes = (bytes: number, precision = 1) => {
    const size = byteSize(bytes, { units: 'iec', precision })

    return `${size.value} ${size.unit}`
}

/**
 * What a device is backed by, said plainly: the image in the drive if there is
 * one, otherwise the volume, otherwise nothing is in it.
 */
export const describeBacking = (device: StorageDevice): string | null => {
    if (deviceKind(device) === 'cloudinit') return 'Generated by the panel'

    return device.mediaName ?? device.volume
}

/**
 * The options that change how a device behaves, dropped when they carry no
 * information. Every disk that is backed up says so; saying "not replicated"
 * about the twenty settings a user never touched is noise.
 */
export const deviceOptions = (device: StorageDevice): string[] => {
    if (deviceKind(device) !== 'disk') return []

    return [
        device.isEmulatingSSD && 'SSD',
        device.discardMode === 'on' && 'Discard',
        device.isIOThreadEnabled && 'IO thread',
        device.isIncludedInBackup && 'Backed up',
        device.isReadonly && 'Read-only',
    ].filter((option): option is string => typeof option === 'string')
}

/**
 * Whether anything in the boot order can actually boot an operating system.
 *
 * A boot order of nothing but the cloud-init drive is syntactically fine and
 * leaves the server sitting at its firmware, which is exactly the state that is
 * impossible to diagnose from a list of bus names.
 */
export const hasBootableDevice = (
    devices: StorageDevice[],
    order: string[]
): boolean =>
    order.some(interfaceName => {
        const device = devices.find(d => d.interface === interfaceName)

        return device !== undefined && deviceKind(device) !== 'cloudinit'
    })

/**
 * Devices in the order the screen lists them: everything that boots, in boot
 * order, then everything that does not, by interface.
 *
 * Only the boot order is persistable, so the devices outside it have no stored
 * position to restore — sorting them keeps the list from reshuffling on every
 * refetch.
 */
export const orderDevices = (
    devices: StorageDevice[],
    order: string[]
): StorageDevice[] => {
    const booting = order
        .map(interfaceName => devices.find(d => d.interface === interfaceName))
        .filter((device): device is StorageDevice => device !== undefined)

    const rest = devices
        .filter(device => !order.includes(device.interface))
        .sort((a, b) =>
            a.interface.localeCompare(b.interface, undefined, {
                numeric: true,
            })
        )

    return [...booting, ...rest]
}
