services:
  app:
    build:
      context: ./dockerfiles/app
      args:
        - APP_ENV=$APP_ENV
        - APP_URL=$APP_URL
        - PHP_XDEBUG=$PHP_XDEBUG
        - PHP_XDEBUG_MODE=$PHP_XDEBUG_MODE
    restart: always
    volumes:
      - .:/app
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    env_file: .env
    tty: true
    extra_hosts:
      host.docker.internal: host-gateway
  horizon:
    build:
      context: ./dockerfiles/app
      args:
        - APP_ENV=$APP_ENV
    command: php /app/artisan horizon
    restart: always
    volumes:
        - .:/app
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
  scheduler:
    build:
      context: ./dockerfiles/app
      args:
        - APP_ENV=$APP_ENV
    command: /bin/sh -c "while [ true ]; do (php /app/artisan schedule:run --verbose --no-interaction &); sleep 60; done"
    restart: always
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
  logrotate:
    build:
      context: ./dockerfiles/logrotate
    restart: always
    volumes:
      - .:/app
  redis:
    image: redis:7.0-alpine
    restart: always
    command: redis-server --save 60 1 --loglevel notice --requirepass '${REDIS_PASSWORD}'
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: redis-cli -a $$REDIS_PASSWORD ping | grep PONG
      interval: 5s
      timeout: 5s
      retries: 20
  database:
    image: mysql:8.0
    restart: always
    volumes:
      - ./dockerfiles/mysql/data:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: mysqladmin ping -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  caddy-config:
  caddy-data: