<?php

/*
 * Generated by `php artisan maintenance:refresh-job-signatures` — do not edit by hand.
 *
 * Every queued job's constructor, as of the last time someone regenerated this. It exists so
 * that changing one shows up in review: a queued payload written by the release you are
 * upgrading *from* is executed by the release you are upgrading *to*, and Convoy's
 * self-polling jobs mean the queue is never reliably empty at that moment.
 *
 * Read App\Support\Jobs\QueuedJobSignatures for the rule this enforces and why a removed,
 * renamed or newly promoted parameter is the thing that breaks an upgrade.
 */

return [
    'App\\Jobs\\Backup\\BatchPurgeServerBackupsJob' => [
        ['name' => 'server', 'type' => 'App\\Models\\Server', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Backup\\DeleteBackupJob' => [
        ['name' => 'backup', 'type' => 'App\\Models\\Backup', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Backup\\WaitUntilBackupIsDeletedJob' => [
        ['name' => 'backup', 'type' => 'App\\Models\\Backup', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Node\\MonitorIsoDownloadJob' => [
        ['name' => 'isoId', 'type' => 'int', 'optional' => false, 'promoted' => true, 'variadic' => false],
        ['name' => 'upid', 'type' => 'string', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Node\\PollNodeStatusJob' => [
        ['name' => 'nodeId', 'type' => 'int', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Node\\PruneUsersJob' => [
        ['name' => 'nodeId', 'type' => 'int', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Node\\SyncServerUsagesJob' => [
        ['name' => 'nodeId', 'type' => 'int', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Server\\BatchSyncNetworkSettingsJob' => [
        ['name' => 'addressBlock', 'type' => 'App\\Models\\AddressBlock', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Server\\CloneVmJob' => [
        ['name' => 'step', 'type' => 'App\\Models\\DeploymentStep', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Server\\ConfigureVmJob' => [
        ['name' => 'step', 'type' => 'App\\Models\\DeploymentStep', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Server\\DeleteVmJob' => [
        ['name' => 'step', 'type' => 'App\\Models\\DeploymentStep', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Server\\MonitorBackupJob' => [
        ['name' => 'backup', 'type' => 'App\\Models\\Backup', 'optional' => false, 'promoted' => true, 'variadic' => false],
        ['name' => 'upid', 'type' => 'string', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Server\\MonitorBackupRestorationJob' => [
        ['name' => 'server', 'type' => 'App\\Models\\Server', 'optional' => false, 'promoted' => true, 'variadic' => false],
        ['name' => 'upid', 'type' => 'string', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Server\\PurgeBackupsJob' => [
        ['name' => 'server', 'type' => 'App\\Models\\Server', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Server\\SendPowerCommandJob' => [
        ['name' => 'step', 'type' => 'App\\Models\\DeploymentStep', 'optional' => false, 'promoted' => true, 'variadic' => false],
        ['name' => 'power', 'type' => 'App\\Enums\\Server\\PowerCommand', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Server\\StopVmJob' => [
        ['name' => 'step', 'type' => 'App\\Models\\DeploymentStep', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Server\\SyncNetworkSettingsJob' => [
        ['name' => 'server', 'type' => 'App\\Models\\Server', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Server\\SyncServerRateLimitJob' => [
        ['name' => 'server', 'type' => 'App\\Models\\Server', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
    'App\\Jobs\\Server\\UpdatePasswordJob' => [
        ['name' => 'step', 'type' => 'App\\Models\\DeploymentStep', 'optional' => false, 'promoted' => true, 'variadic' => false],
        ['name' => 'password', 'type' => 'string', 'optional' => false, 'promoted' => true, 'variadic' => false],
    ],
];
