<?php

namespace App\Services\Servers;

use App\Services\ProxmoxService;

class NetworkService extends ProxmoxService
{
    public function getIpSets()
    {
        return $this->removeDataProperty($this->instance()->firewall()->ipSet()->get());
    }

    public function getLockedIps(string $ipSetName)
    {
        return $this->removeDataProperty($this->instance()->firewall()->ipSet()->name($ipSetName)->get());
    }

    public function createIpSet(string $name, string $comments = 'Generated by Convoy')
    {
        return $this->instance()->firewall()->ipSet()->post([
            'name' => $name,
            'comment' => $comments,
        ]);
    }

    public function lockIp(string $ipSetName, string $address, string $comments = 'Generated by Convoy', bool $noMatch = false)
    {
        return $this->removeDataProperty($this->instance()->firewall()->ipSet()->name($ipSetName)->post([
            'cidr' => $address,
            'nomatch' => $noMatch,
            'comment' => $comments,
        ]));
    }
}