<?php

namespace App\Console\Commands\Maintenance;

use App\Support\Jobs\QueuedJobSignatures;
use Illuminate\Console\Command;

/**
 * Regenerates the queued-job constructor snapshot that {@see QueuedJobSignatures} documents.
 *
 * A development-time command, not something an install runs: it rewrites a file in the source tree
 * and expects whoever ran it to review the diff. The test suite fails while the snapshot is stale,
 * which is what forces a change to a job's constructor through a human's eyes instead of shipping
 * quietly and stranding whatever that job had queued at upgrade time.
 */
class RefreshJobSignaturesCommand extends Command
{
    /**
     * @var string
     */
    protected $signature = 'maintenance:refresh-job-signatures {--check : Report drift and exit non-zero without writing the snapshot.}';

    /**
     * @var string
     */
    protected $description = 'Regenerates the snapshot of queued job constructors used to catch payload-incompatible changes.';

    public function handle(): int
    {
        $current = QueuedJobSignatures::current();

        if ($current === QueuedJobSignatures::recorded()) {
            $this->info('Job signatures are up to date ('.count($current).' jobs).');

            return self::SUCCESS;
        }

        if ($this->option('check')) {
            $this->error('The job signature snapshot is out of date. Run `php artisan maintenance:refresh-job-signatures` and review the diff.');

            return self::FAILURE;
        }

        file_put_contents(QueuedJobSignatures::SNAPSHOT, $this->render($current));

        $this->info('Wrote '.count($current).' job signatures. Review the diff before committing — a removed or renamed parameter strands whatever is already on the queue.');

        return self::SUCCESS;
    }

    /**
     * @param  array<class-string, list<array<string, bool|string>>>  $signatures
     */
    private function render(array $signatures): string
    {
        $body = '';

        foreach ($signatures as $class => $parameters) {
            $body .= '    '.var_export($class, true)." => [\n";

            foreach ($parameters as $parameter) {
                $pairs = [];

                foreach ($parameter as $key => $value) {
                    $pairs[] = var_export($key, true).' => '.var_export($value, true);
                }

                $body .= '        ['.implode(', ', $pairs)."],\n";
            }

            $body .= "    ],\n";
        }

        return <<<PHP
        <?php

        /*
         * Generated by `php artisan maintenance:refresh-job-signatures` — do not edit by hand.
         *
         * Every queued job's constructor, as of the last time someone regenerated this. It exists so
         * that changing one shows up in review: a queued payload written by the release you are
         * upgrading *from* is executed by the release you are upgrading *to*, and Convoy's
         * self-polling jobs mean the queue is never reliably empty at that moment.
         *
         * Read App\\Support\\Jobs\\QueuedJobSignatures for the rule this enforces and why a removed,
         * renamed or newly promoted parameter is the thing that breaks an upgrade.
         */

        return [
        {$body}];

        PHP;
    }
}
