<?php

namespace App\Repositories\Proxmox\Server;

use App\Data\Server\Proxmox\Network\IpsetData;
use App\Data\Server\Proxmox\Network\LockedIpData;
use App\Exceptions\Repository\Proxmox\RequestException;
use App\Repositories\Proxmox\ProxmoxRepository;
use Illuminate\Support\Arr;
use Illuminate\Support\Collection;
use IPLib\Factory;
use IPLib\Range\RangeInterface;

class ProxmoxFirewallRepository extends ProxmoxRepository
{
    /**
     * @throws RequestException
     */
    public function updateOptions(array $payload)
    {
        $response = $this->getHttpClientWithParams()
            ->put('/api2/json/nodes/{node}/qemu/{server}/firewall/options', $payload)
            ->json();

        return $this->getData($response);
    }

    /**
     * @return Collection<int, IpsetData>
     *
     * @throws RequestException
     */
    public function getIpsets(): Collection
    {
        $response = $this->getHttpClientWithParams()
            ->get('/api2/json/nodes/{node}/qemu/{server}/firewall/ipset')
            ->json();

        return IpsetData::collect(Arr::map($this->getData($response), function (array $item) {
            /** @var array{ name: string, digest: string} $item */

            return [
                'name' => $item['name'],
                'comment' => $item['comment'] ?? null,
            ];
        }), Collection::class);
    }

    /**
     * @throws RequestException
     */
    public function createIpset(string $name, string $comments = 'Generated by Convoy'): void
    {
        $this->getHttpClientWithParams()
            ->post('/api2/json/nodes/{node}/qemu/{server}/firewall/ipset', [
                'name' => $name,
                'comment' => $comments,
            ]);
    }

    /**
     * @throws RequestException
     */
    public function deleteIpset(string|IpsetData $ipset): void
    {
        if ($ipset instanceof IpsetData) {
            $ipset = $ipset->name;
        }

        $this->getHttpClientWithParams([
            'ipset' => $ipset,
        ])
            ->delete('/api2/json/nodes/{node}/qemu/{server}/firewall/ipset/{ipset}');
    }

    /**
     * @return Collection<int, LockedIpData>
     *
     * @throws RequestException
     */
    public function getLockedIps(string|IpsetData $ipset): Collection
    {
        if ($ipset instanceof IpsetData) {
            $ipset = $ipset->name;
        }

        $response = $this->getHttpClientWithParams([
            'ipset' => $ipset,
        ])
            ->get('/api2/json/nodes/{node}/qemu/{server}/firewall/ipset/{ipset}')
            ->json();

        return LockedIpData::collect(Arr::map($this->getData($response), function (array $item) {
            /** @var array{ cidr: string, comment: ?string, digest: string} $item */

            return [
                'ip' => Factory::parseRangeString($item['cidr']),
                'comment' => $item['comment'] ?? null,
                'originalIp' => $item['cidr'],
            ];
        }), Collection::class);
    }

    /**
     * @throws RequestException
     */
    public function lockIp(string|IpsetData $ipset, string|RangeInterface $ip, string $comments = 'Generated by Convoy'): void
    {
        if ($ipset instanceof IpsetData) {
            $ipset = $ipset->name;
        }

        if ($ip instanceof RangeInterface) {
            $ip = $ip->toString();
        }

        $this->getHttpClientWithParams([
            'ipset' => $ipset,
        ])
            ->post('/api2/json/nodes/{node}/qemu/{server}/firewall/ipset/{ipset}', [
                'cidr' => $ip,
                'nomatch' => false,
                'comment' => $comments,
            ]);
    }

    /**
     * @throws RequestException
     */
    public function unlockIp(string|IpsetData $ipset, string|RangeInterface|LockedIpData $ip): void
    {
        if ($ipset instanceof IpsetData) {
            $ipset = $ipset->name;
        }

        if ($ip instanceof RangeInterface) {
            $ip = $ip->toString();
        }

        if ($ip instanceof LockedIpData) {
            $ip = $ip->originalIp;
        }

        $this->getHttpClientWithParams([
            'ipset' => $ipset,
            'address' => $ip,
        ])
            ->delete('/api2/json/nodes/{node}/qemu/{server}/firewall/ipset/{ipset}/{address}');
    }
}
