<?php

namespace App\Support\Passkeys;

use App\Console\Commands\Maintenance\RefreshAuthenticatorAaguidsCommand;
use App\Models\Passkey;
use Symfony\Component\Uid\AbstractUid;

/**
 * Maps an authenticator's AAGUID — the identifier a WebAuthn authenticator reports for its make
 * and model — onto the name a person would recognise it by ("1Password", "Bitwarden", "Windows
 * Hello", "YubiKey 5 Series"). We use it to give a freshly registered passkey a meaningful default
 * name instead of a datestamp, so the list in account settings is readable even if the user never
 * renames anything.
 *
 * The table itself lives in {@see self::TABLE}, generated by
 * {@see RefreshAuthenticatorAaguidsCommand}. It is deliberately a vendored snapshot rather than
 * something fetched at runtime: Convoy is self-hosted, and no install should need to reach
 * GitHub in the middle of a passkey registration. Staleness is harmless — an authenticator we
 * don't recognise falls back to a datestamp, which is what every passkey used to get.
 *
 * Not every authenticator is in the table, and browsers may report an all-zero AAGUID, so
 * {@see self::nameFor()} is always allowed to come back empty.
 */
final class AuthenticatorAaguids
{
    /** The generated lookup table. Rewritten wholesale by the refresh command. */
    public const TABLE = __DIR__.'/authenticator-names.php';

    /** @var array<string, string>|null */
    private static ?array $names = null;

    /**
     * The whole table, keyed by lowercase AAGUID.
     *
     * @return array<string, string>
     */
    public static function names(): array
    {
        return self::$names ??= require self::TABLE;
    }

    /**
     * Drops the memoised copy. Only {@see RefreshAuthenticatorAaguidsCommand} needs this — it
     * rewrites the table out from under us, and anything reading it afterwards wants the new one.
     */
    public static function forget(): void
    {
        self::$names = null;
    }

    /**
     * The recognisable name for an authenticator, or null when we don't know it — either because
     * the authenticator is absent from the table or because it reported no AAGUID at all (an
     * all-zero AAGUID, which some browsers substitute for privacy).
     */
    public static function nameFor(AbstractUid|string|null $aaguid): ?string
    {
        if ($aaguid === null) {
            return null;
        }

        $aaguid = mb_strtolower($aaguid instanceof AbstractUid ? $aaguid->toRfc4122() : $aaguid);

        if ($aaguid === '00000000-0000-0000-0000-000000000000') {
            return null;
        }

        return self::names()[$aaguid] ?? null;
    }

    /**
     * Turns a raw name from either upstream source into something worth showing a person.
     *
     * The FIDO Metadata Service describes authenticators for auditors, not end users, so its
     * descriptions carry distribution qualifiers that mean nothing here — "(Enterprise Profile)",
     * "Preview", the CTAP versions it speaks, internal batch codes. Those come off, and what is
     * left is trimmed on a word boundary to {@see Passkey::NAME_MAX_LENGTH} so a name we assign
     * automatically is always one a rename would accept back.
     *
     * Returns an empty string when nothing usable survives; callers should skip those.
     */
    public static function displayName(string $raw): string
    {
        $name = preg_replace(
            [
                '/\s*\((?:Enterprise|Consumer)\s+Profile\)/i',
                '/\s*\((?:RC\s+)?Preview\)/i',
                '/\s*\(CTAP[^)]*\)/i',
                '/\s*\b(?:Draft|Preview)\b/',
                // A trailing internal batch code, e.g. "YubiKey 5 Series with NFC KVZR57-2".
                '/\s+(?=[A-Z0-9-]*[A-Z])(?=[A-Z0-9-]*\d)[A-Z0-9]{5,}(?:-\d+)?$/',
                '/\s+/',
            ],
            ['', '', '', '', '', ' '],
            trim($raw),
        );

        $name = trim($name, " -\t\n\r\0\x0B");

        if (mb_strlen($name) > Passkey::NAME_MAX_LENGTH) {
            $name = mb_substr($name, 0, Passkey::NAME_MAX_LENGTH + 1);
            $name = mb_substr($name, 0, max(0, (int) mb_strrpos($name, ' ')));
            // A cut can leave a dangling connective ("... FIDO 2.1 v1.0 by").
            $name = preg_replace('/\s+(?:by|from|with|for|and|the|of|an?)$/i', '', $name);
        }

        return trim($name, " -\t\n\r\0\x0B");
    }
}
