name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Update Embedded Version String
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          sed -i "s/    'version' => 'canary',/    'version' => '${VERSION#v}',/" config/app.php

      - name: Build Assets
        run: |
          npm ci
          npm run build

      - name: Create Release Archive
        run: |
          files_to_remove=(
            "node_modules/"
            "tests/"
            "CODE_OF_CONDUCT.md"
            "CONTRIBUTOR_LICENSE_AGREEMENT"
            "crowdin.yml"
            "phpstan.neon"
            "phpunit.xml"
            "stats.html"
          )
          rm -rf "${files_to_remove[@]}"

          files_to_include=(
            ".editorconfig"
            ".env.example"
            ".env.full_example"
            ".gitattributes"
            ".gitignore"
            ".prettierignore"
            ".prettierrc.json"
          )

          tar --exclude=panel.tar.gz -czf panel.tar.gz * "${files_to_include[@]}"

      - name: Extract Changelog
        id: extract_changelog
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          sed -n "/^## ${VERSION}/,/^## /{/^## /b;p}" CHANGELOG.md > ./RELEASE_CHANGELOG
          echo "version_name=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Create Checksum and Add to Changelog
        run: |
          SUM=$(sha256sum panel.tar.gz)
          printf "\n#### SHA256 Checksum\n\n\`\`\`\n%s\n\`\`\`\n" "$SUM" >> ./RELEASE_CHANGELOG
          echo "$SUM" > checksum.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.extract_changelog.outputs.version_name }}
          body_path: ./RELEASE_CHANGELOG
          draft: true
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'rc') }}
          files: |
            panel.tar.gz
            checksum.txt
